name    'lcgdm-gridftp'
version '0.1.1'
source 'UNKNOWN'
author 'puppet'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'This package installs and configures a gridftp server'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
